//discover
export const GET_DISCOVER_START = "GET_DISCOVER_START"
export const GET_DISCOVER_SUCCESS = "GET_DISCOVER_SUCCESS"
export const GET_DISCOVER_FAILED = "GET_DISCOVER_FAILED"
//nowPlaying
export const GET_NOW_PLAYING_START = "GET_NOW_PLAYING_START"
export const GET_NOW_PLAYING_SUCCESS = "GET_NOW_PLAYING_SUCCESS"
export const GET_NOW_PLAYING_FAILED = "GET_POPULAR_FALED"
//trending day
export const GET_TRENDING_DAY_START = "GET_TRENDING_DAY_START"
export const GET_TRENDING_DAY_SUCCESS = "GET_TRENDING_DAY_SUCCESS"
export const GET_TRENDING_DAY_FAILED = "GET_TRENDING_DAY_FAILED"
//trending week
export const GET_TRENDING_WEEK_START = "GET_TRENDING_WEEK_START"
export const GET_TRENDING_WEEK_SUCCESS = "GET_TRENDING_WEEK_SUCCESS"
export const GET_TRENDING_WEEK_FAILED = "GET_TRENDING_WEEK_FAILED"
//popular
export const GET_POPULAR_START = "GET_POPULAR_START"
export const GET_POPULAR_SUCCESS = "GET_POPULAR_SUCCESS"
export const GET_POPULAR_FAILED = "GET_POPULAR_FAILED"
//top rated
export const GET_TOP_RATED_START = "GET_TOP_RATED_START"
export const GET_TOP_RATED_SUCCESS = "GET_TOP_RATED_SUCCESS"
export const GET_TOP_RATED_FAILED = "GET_TOP_RATED_FAILED"
//upcoming
export const GET_UPCOMING_START = "GET_UPCOMING_START"
export const GET_UPCOMING_SUCCESS = "GET_UPCOMING_SUCCESS"
export const GET_UPCOMING_FAILED = "GET_UPCOMING_FAILED"
//tvshow
export const GET_TV_START = "GET_TV_START"
export const GET_TV_SUCCESS = "GET_TV_SUCCESS"
export const GET_TV_FAILED = "GET_TV_FAILED"
//detail
export const GET_DETAIL_START = "GET_DETAIL_START"
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS"
export const GET_DETAIL_FAILED = "GET_DETAIL_FAILED"
